# Generated by Django 3.2.4 on 2021-06-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210608_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
