# Generated by Django 3.2.4 on 2021-06-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210608_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
